### ISSUE TITLE
API for modifying config, e.g., for turning logging on and off

### ISSUE THREAD

**Issue by artgoldberg** [KarrLab/wc_utils#16]

**Comment by jonrkarr** [comment]
There are already multiple ways to override the default config:

- Supply a `.cfg` file in the current directory or in your `~/.wc/` directory
- Assign environment variables with `__DOT__` as the separator for levels in the hierarchy, e.g.
  `config['karr_lab_build_utils']['configs_repo_password']='<val>'`
  becomes
  `CONFIG__DOT__karr_lab_build_utils__DOT__configs_repo_password=<val>`
- Use the optional `extra` argument to `get_config`, e.g.
  `ConfigManager.get_config(extra={ ... })`
   with extra:
  ```
  {
      'karr_lab_build_utils': {
          'configs_repo_password': '<val>',
      },
  }
  ```
